// <auto-generated />
using System;
using System.Collections.Generic;
using Comercios.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Comercios.Migrations
{
    [DbContext(typeof(ComerciosDbContext))]
    partial class ComerciosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("comercios")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Comercios.Domain.Entities.Comercio", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<bool>("Abierto")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Calificacion")
                        .HasColumnType("numeric");

                    b.Property<List<string>>("Categorias")
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImgBannerUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Usuario_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Comercios", "comercios");
                });

            modelBuilder.Entity("Comercios.Domain.Entities.DatosComercio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comercio_id")
                        .IsRequired()
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Comercio_id")
                        .IsUnique();

                    b.ToTable("DatosComercio", "comercios");
                });

            modelBuilder.Entity("Comercios.Domain.Entities.DatosComercio", b =>
                {
                    b.HasOne("Comercios.Domain.Entities.Comercio", "Comercio")
                        .WithOne("InfoComercio")
                        .HasForeignKey("Comercios.Domain.Entities.DatosComercio", "Comercio_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("Comercios.Domain.Entities.Comercio", b =>
                {
                    b.Navigation("InfoComercio");
                });
#pragma warning restore 612, 618
        }
    }
}
